apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators-prod

resources:
- ../../operators

patchesStrategicMerge:
- patches.yaml

commonLabels:
  environment: prod
  managed-by: kustomize
