apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators-staging

resources:
- ../../operators

patchesStrategicMerge:
- patches.yaml

commonLabels:
  environment: staging
  managed-by: kustomize
