namespace: openshift-gitops-operator
subscription:
  name: openshift-gitops-operator
  channel: latest
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

