apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: openshift-operators-dev

resources:
- ../../operators

patchesStrategicMerge:
- patches.yaml

commonLabels:
  environment: dev
  managed-by: kustomize
