apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: acs-og
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | default "Helm" }}
  annotations:
    meta.helm.sh/release-name: {{ .Release.Name }}
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  targetNamespaces:
  - {{ .Values.namespace }}

