namespace: openshift-operators
subscription:
  name: trusted-artifact-signer-operator
  channel: stable
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Automatic

